### ISSUE TITLE
please

### ISSUE THREAD

**Issue by MrDoni98** [organization/PmChair#1]
add a double tap

**Comment by HmHmmHm** [comment]
what double tap?

**Comment by MrDoni98** [comment]
In EconomyS double tap it is
public function setDoubleTap(Player $player, $tag){
        $this->doubleTap[$player->getName()] = array(
            "id" => $tag,
            "time" => microtime(true)
        );
}

**Comment by MrDoni98** [comment]
with my bad English)

**Comment by HmHmmHm** [comment]
...? i know php syntax but i can't understand what your want

**Comment by MrDoni98** [comment]
A player can accidentally tap on the stairs when it is rising, and it's not convenient. And if you use double tap it can be avoided.

**Comment by HmHmmHm** [comment]
hmm... that's not bad
@wsj7178 now you have to more work :p

**Comment by MrDoni98** [comment]
@_>

**Comment by wsj7178** [comment]
ok, i got it

**Comment by wsj7178** [comment]
@MrDoni98 I update it for you!
And I added messages.yml
