### ISSUE TITLE
I can't guess unknown byte in SetEntityLinkPacket.php

### ISSUE THREAD

**Issue by nnnlog** [organization/PmChair#8]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/SetEntityLinkPacket.php#L34

I can guess [from, to, type] but I don't know unknown byte.

PmChair doesn't work.

**Comment by SeungjunWe** [comment]
언제적 이슈를 이제와서 닫누

**Comment by nnnlog** [comment]
@SeungjunWe 아 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
